### ISSUE TITLE
Error: Cannot read property 'identifier' of null

### ISSUE THREAD

**Issue by armarti** [tomesparon/OpenVMS-DCL-VSCODE-Lang-Support#1]
Hi there, one of the last DCL writers here, thanks for your extension. I can't install the extension through the standard extension install method in the editor. I get this stacktrace:

![image](https://user-images.githubusercontent.com/13367887/53430939-6ff3fb80-39e7-11e9-8326-61e92c9cb67f.png)

Then when I download the .vsix file and install manually, my .COM files aren't highlighted. I suspect this is because there isn't a language like DCL / OpenVMS / VMS available to associate .COM files with

My vscode stats:
- Version: 1.30.1 (user setup)
- Commit: dea8705087adb1b5e5ae1d9123278e178656186a
- Date: 2018-12-18T18:12:07.165Z
- Electron: 2.0.12
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- OS: Windows_NT x64 10.0.17134

**Comment by armarti** [comment]
Ah now when I try to install the .vsix file via `CTRL+P > Extensions: Install from VSIX...` I get "Unable to install extension 'tomesparon.openvms-syntax-0.1.0' as it is not compatible with VS Code '1.30.1'."

**Comment by armarti** [comment]
Okay updating to 1.31.1 makes it work. Feel free to close!

**Comment by tomesparon** [comment]
Cheers for this, ill try to change the version requirements so this doesnt happen
